<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
  <!-- ===== Basic Info ===== -->
    <meta charset="utf-8">
    <title>TeamAccess: <?php echo strtoupper($portal['host']); ?></title>
    <meta name="description" content="TeamAccess: <?php echo strtoupper($portal['host'])." | ".$portal['fqdn']; ?> ">
    <meta name="author" content="Team Access: Chas Lesley">
  <!-- ===== Mobile Info ===== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!-- ===== CSS Includes ===== -->
    <link rel="stylesheet" href="./css/zerogrid.css">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/lightbox.css">
    <link rel="stylesheet" href="./css/menu.css">
  <!-- ===== Custom Fonts ===== -->
    <link href="./font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <!-- ===== Scripts ===== -->
    <script src="./js/jquery1111.min.js" type="text/javascript"></script>
    <script src="./js/script.js"></script>
  <!-- ===== Browser FixUp ===== -->
    <!--[if lt IE 8]>
      <div style=' clear: both; text-align:center; position: relative;'>
        <a href="http://windows.microsoft.com/en-US/internet-explorer/Items/ie/home?ocid=ie6_countdown_bannercode">
          <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
      <script src="./js/html5.js"></script>
      <script src="./js/css3-mediaqueries.js"></script>
    <![endif]-->
</head>
