<!--#### CONTENT: info ##### -->
  <!-----------------start-content-box-3-------------------->
    <section class="content-box boxstyle-2 box-3">
      <div class="zerogrid">
        <div class="row wrap-box">
          <div class="header">
            <div class="wrapper">
              <div class="intro">Information & Links</div>
              <hr class="line">
              <div class="lead">Below is a collection of information & links to key content we most often share. The sections below are subdivided into knowledge areas that may prove useful in your F5 design, configuration & trouble-shooting tasks. Enjoy!</div>
            </div>
          </div>
          <div class="row">
            <?php
              imglinks("kids1-thumb.jpg","single.html","LOREM IPSUM","Some stuff i typed");
              imglinks("kids2-thumb.jpg","single.html","LOREM IPSUM","Some stuff i typed");
              imglinks("kids3-thumb.jpg","single.html","LOREM IPSUM","Some stuff i typed");
              imglinks("kids4-thumb.jpg","single.html","LOREM IPSUM","Some stuff i typed");
            ?>
          </div>
        </div>
      </div>
    </section>
  <!-----------------end-content-box-3-------------------->
