<?php
  $users = array(
    "user1@f5lab.local" => array (
      "image" => "coyote.png",
      "name" => "Lab User1",
      "title" => "Senior Systems Engineer"
    ),
    "user2@f5lab.local" => array (
      "image" => "runner.png",
      "name" => "Lab User2",
      "title" => "Product Development Architect"
    ),
    "user3@f5lab.local" => array (
      "image" => "martian.png",
      "name" => "Lab User3",
      "title" => "Product Manager"
    ),
    "1234567890@f5lab.local" => array (
      "image" => "martian.png",
      "name" => "Lab User3",
      "title" => "Product Manager"
    )
  );
?>
