<?php
// VS Status Icons
  $up_monitor_enabled="grn_circle";
  $up_monitor_disabled="yel_triangle";
  $up_user_disabled="blk_circle";
  $down_monitor_enabled="red_diamond";
  $down_user_disabled="blk_diamond";
  $user_down="blk_diamond";
  $unchecked_user_enabled="blue_square";
  $unchecked_user_disabled="blk_diamond";
  $available_enabled="grn_circle";

// Pool Status Icons
  $unknown_enabled="blue_square";
  $unknown_disabled="blk_square";
  $offline_disabled="blk_diamond";
  $offline_enabled="red_diamond";
  $available_disabled="blk_circle";
  $available_enabled="grn_circle";
  $offline_disabled_by_parent="gry_diamond";
  $available_disabled_by_parent="gry_circle";

// Member Status Icons
  $user_down_user_disabled="blk_diamond";
  $user_down_user_enabled="red_diamond";
  $user_down_monitor_enabled="red_diamond";
  $fqdn_up_user_enabled="grn_circle";
  $fqdn_up_user_disabled="blk_circle";
  $down_user_enabled="red_diamond";
?>

